# Generated by Django 4.2.9 on 2024-02-02 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='行为名称')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='url')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='日志创建时间')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户名')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='账号')),
                ('ip', models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.validate_ipv46_address], verbose_name='ip地址')),
            ],
            options={
                'db_table': 'log',
            },
        ),
    ]
